const VIEWS = ["overview", "product", "business", "workflow", "domain", "experience", "architecture", "verification", "impact"];
const labels = { overview: "Overview", product: "Product", business: "Business", workflow: "Workflow", domain: "Domain", experience: "Experience", architecture: "Architecture", verification: "Verification", impact: "Impact" };
const viewRegions = { overview: null, product: ["intent", "product", "quality"], business: ["business", "intent", "product"], workflow: ["workflow", "product", "business"], domain: ["domain", "business", "workflow"], experience: ["experience", "workflow", "domain", "product"], architecture: ["architecture", "domain", "experience", "quality"], verification: ["quality", "decision", "product"], impact: null };
const regions = ["intent", "product", "business", "workflow", "domain", "experience", "architecture", "decision", "quality"];
const colors = { intent: "#f4bc7a", product: "#75e0c2", business: "#ef9bca", workflow: "#e6b86a", domain: "#81c8ff", experience: "#90d7bb", architecture: "#bd9aff", decision: "#ff8d8d", quality: "#b8c8ff" };
const state = { graph: null, baseline: null, diagnostics: [], focusAreas: [], tours: [], library: { patterns: [], templates: [] }, proposals: [], scope: { id: "project", title: "Product graph", rootIds: [], depth: 2 }, view: "overview", search: "", selectedId: null, context: null, compare: null, drawer: "context", dirty: false, history: [], future: [], layout: {}, scopeBack: [], scopeForward: [], tour: null, dragging: null };
const $ = (id) => document.getElementById(id);

async function request(url, options) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Request failed"); return data; }
function regionOf(node) { return node.region || ({ document: "experience", roadmap: "product" }[node.layer] || node.layer || "product"); }
function scopeKey() { return `${state.scope.id}:${state.view}`; }
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function snapshot() { return { graph: clone(state.graph), layout: clone(state.layout) }; }
function restore(value) { state.graph = value.graph; state.layout = value.layout; }
function nodeById(id) { return state.graph.nodes.find((node) => node.id === id); }
function relatedIds(ids, depth) { const seen = new Set(ids); let frontier = new Set(ids); for (let i = 0; i < depth; i += 1) { const next = new Set(); for (const edge of state.graph.edges) { if (frontier.has(edge.from)) next.add(edge.to); if (frontier.has(edge.to)) next.add(edge.from); } next.forEach((id) => seen.add(id)); frontier = next; } return seen; }
function scopedNodes() { const roots = state.scope.rootIds; const ids = roots.length ? relatedIds(roots, state.scope.depth) : null; const allowed = viewRegions[state.view]; return state.graph.nodes.filter((node) => (!ids || ids.has(node.id)) && (!allowed || allowed.includes(regionOf(node))) && (state.view !== "impact" || !roots.length || node.id !== roots[0]) && `${node.id} ${node.title} ${node.type}`.toLowerCase().includes(state.search.toLowerCase())); }
function selectedNode() { return nodeById(state.selectedId); }
function commit(mutator) { state.history.push(snapshot()); state.future = []; mutator(); markDirty(); render(); }
function undo() { if (!state.history.length) return; state.future.push(snapshot()); restore(state.history.pop()); markDirty(); render(); toast("Undid last change"); }
function redo() { if (!state.future.length) return; state.history.push(snapshot()); restore(state.future.pop()); markDirty(); render(); toast("Redid change"); }
function markDirty() { state.dirty = true; setStatus("Unsaved changes", true); }
function setStatus(text, dirty = state.dirty) { $("save-state").textContent = dirty ? "Unsaved changes" : text; $("save-state").style.color = dirty ? "#e6b86a" : ""; $("undo-button").disabled = !state.history.length; $("redo-button").disabled = !state.future.length; $("back-button").disabled = !state.scopeBack.length; $("forward-button").disabled = !state.scopeForward.length; }
function toast(message) { const node = $("toast"); node.textContent = message; node.classList.add("show"); setTimeout(() => node.classList.remove("show"), 2300); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char])); }
function trim(value, length) { return value.length > length ? `${value.slice(0, length - 1)}…` : value; }

function renderFocusAreas() {
  $("focus-area-list").innerHTML = `<button class="layer-button ${state.scope.id === "project" ? "active" : ""}" data-focus="project" type="button"><i class="layer-icon"></i><span class="layer-label">Overview</span><span class="layer-number">${state.graph.nodes.length}</span></button>` + state.focusAreas.map((area) => `<button class="layer-button ${state.scope.id === area.id ? "active" : ""}" data-focus="${escapeHtml(area.id)}" type="button"><i class="layer-icon"></i><span class="layer-label"><strong>${escapeHtml(area.title)}</strong><small>${escapeHtml(area.description || "Focus area")}</small></span><span class="layer-number">${area.rootIds.length}</span></button>`).join("");
  document.querySelectorAll("[data-focus]").forEach((button) => button.addEventListener("click", () => { if (button.dataset.focus === "project") setScope({ id: "project", title: "Product graph", rootIds: [], depth: 2 }, false); else { const area = state.focusAreas.find((item) => item.id === button.dataset.focus); if (area) setScope({ id: area.id, title: area.title, rootIds: area.rootIds, depth: area.depth }, false, area.defaultView); } }));
  $("node-count").textContent = `${state.graph.nodes.length} nodes`;
}
function renderLenses() { $("lens-list").innerHTML = VIEWS.map((view) => `<button class="lens-button ${state.view === view ? "active" : ""}" data-lens="${view}" role="tab" aria-selected="${state.view === view}" type="button">${labels[view]}</button>`).join(""); document.querySelectorAll("[data-lens]").forEach((button) => button.addEventListener("click", () => { state.view = button.dataset.lens; render(); })); }
function renderNodeList() { const nodes = scopedNodes(); $("node-list").innerHTML = nodes.length ? nodes.map((node) => `<button class="node-button ${node.id === state.selectedId ? "active" : ""}" data-node="${escapeHtml(node.id)}" type="button"><i class="layer-icon" style="background:${colors[regionOf(node)] || "#91a0b4"}"></i><span class="node-copy"><strong>${escapeHtml(node.title)}</strong><small>${escapeHtml(regionOf(node))} · ${escapeHtml(node.type)}</small></span></button>`).join("") : `<p class="muted" style="padding:.5rem">No objects in this scope/lens.</p>`; document.querySelectorAll("[data-node]").forEach((button) => button.addEventListener("click", () => selectNode(button.dataset.node))); }
function positionFor(node, index) { const stored = state.layout[scopeKey()]?.positions?.[node.id]; if (stored && Number.isFinite(stored.x) && Number.isFinite(stored.y)) return stored; return { x: 150 + (index % 3) * 285, y: 120 + Math.floor(index / 3) * 145 }; }
function renderGraph() { const svg = $("graph-svg"); const nodes = scopedNodes(); const positioned = nodes.map((node, index) => ({ node, ...positionFor(node, index) })); const byId = new Map(positioned.map((item) => [item.node.id, item])); $("empty-state").hidden = nodes.length > 0; $("active-layer").textContent = `${state.scope.title} · ${labels[state.view]}`.toUpperCase(); $("scope-title").textContent = state.scope.title; $("canvas-summary").textContent = `${nodes.length} objects in this semantic scope · depth ${state.scope.depth}`; const edges = state.graph.edges.filter((edge) => byId.has(edge.from) && byId.has(edge.to)); svg.innerHTML = `<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#496274"></path></marker></defs>` + edges.map((edge) => { const a = byId.get(edge.from); const b = byId.get(edge.to); const active = state.selectedId === edge.from || state.selectedId === edge.to; return `<line class="edge-line ${active ? "highlight" : ""}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" />`; }).join("") + positioned.map(({ node, x, y }) => `<g class="graph-node ${node.id === state.selectedId ? "selected" : ""}" data-graph-node="${escapeHtml(node.id)}" transform="translate(${x - 100},${y - 30})" tabindex="0" role="button" aria-label="${escapeHtml(node.title)}, ${escapeHtml(regionOf(node))} node"><rect class="node-card" width="200" height="60" rx="10"></rect><line class="node-accent accent-${regionOf(node)}" x1="2" y1="10" x2="2" y2="50"></line><text class="node-title" x="17" y="27">${escapeHtml(trim(node.title, 24))}</text><text class="node-type" x="17" y="45">${escapeHtml(regionOf(node))} · ${escapeHtml(node.type)}</text></g>`).join(""); document.querySelectorAll("[data-graph-node]").forEach((node) => { node.addEventListener("click", () => selectNode(node.dataset.graphNode)); node.addEventListener("keydown", (event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); selectNode(node.dataset.graphNode); } }); node.addEventListener("pointerdown", (event) => startDrag(event, node.dataset.graphNode)); }); }
function startDrag(event, id) { if (event.button !== 0) return; const before = snapshot(); const move = (moveEvent) => { const rect = $("graph-svg").getBoundingClientRect(); const x = ((moveEvent.clientX - rect.left) / rect.width) * 1000; const y = ((moveEvent.clientY - rect.top) / rect.height) * 680; state.layout[scopeKey()] ||= { schemaVersion: "1.0.0", positions: {} }; state.layout[scopeKey()].positions[id] = { x, y, pinned: true }; renderGraph(); }; const end = () => { state.history.push(before); state.future = []; markDirty(); render(); window.removeEventListener("pointermove", move); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", end, { once: true }); }

async function selectNode(id) { state.selectedId = id; render(); try { const response = await request(`/api/context?rootId=${encodeURIComponent(id)}&depth=${state.scope.depth}`); state.context = response.context; renderInspector(); } catch (error) { toast(error.message); } }
function setScope(scope, push = true, view = state.view) { if (push) { state.scopeBack.push({ ...state.scope }); state.scopeForward = []; } state.scope = scope; state.view = view; state.selectedId = scope.rootIds[0] || null; state.context = null; render(); if (state.selectedId) selectNode(state.selectedId); }
function renderInspector() { const node = selectedNode(); const form = $("node-form"); $("inspector-empty").hidden = Boolean(node); form.hidden = !node; $("context-sections").hidden = !node; $("selection-type").textContent = node ? `${regionOf(node)} / ${node.type}` : "No selection"; if (!node) return; $("node-title").value = node.title; $("node-id").value = node.id; $("node-type").value = node.type; $("node-status").value = node.status || ""; $("node-data").value = JSON.stringify(node.data || {}, null, 2); $("node-region").innerHTML = regions.map((region) => `<option value="${region}" ${regionOf(node) === region ? "selected" : ""}>${region}</option>`).join(""); const edges = state.graph.edges.filter((edge) => edge.from === node.id || edge.to === node.id); $("edge-list").innerHTML = edges.length ? edges.map((edge) => `<div class="edge-item"><strong>${escapeHtml(edge.kind)}</strong><br>${escapeHtml(edge.from)} → ${escapeHtml(edge.to)}</div>`).join("") : `<span class="muted">No relationships yet.</span>`; const context = state.context; if (!context) { ["why-list", "where-list", "impact-list", "source-list"].forEach((id) => $(id).innerHTML = `<span class="muted">Loading context…</span>`); return; } renderContextList("why-list", context.why, "No intent or rationale linked yet."); renderContextList("where-list", context.whereUsed, "No other usage found in this scope."); renderContextList("impact-list", context.impact, "No downstream impact found."); renderContextList("source-list", [...context.decisions, ...context.evidence], "No decisions or evidence linked yet."); }
function renderContextList(id, items, empty) { $(id).innerHTML = items.length ? items.slice(0, 8).map((item) => `<div class="context-item"><button data-node="${escapeHtml(item.id)}" type="button"><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(regionOf(item))} · ${escapeHtml(item.type)}</span></button></div>`).join("") : `<span class="muted">${empty}</span>`; document.querySelectorAll(`#${id} [data-node]`).forEach((button) => button.addEventListener("click", () => selectNode(button.dataset.node))); }
function renderValidation() { const diagnostics = state.diagnostics || []; $("validation-count").textContent = `${diagnostics.length} issue${diagnostics.length === 1 ? "" : "s"}`; $("validation-list").innerHTML = diagnostics.length ? diagnostics.slice(0, 8).map((item) => `<div class="edge-item"><strong>${escapeHtml(item.code || item.level)}</strong><br>${escapeHtml(item.message)}</div>`).join("") : `<span class="muted">No actionable issues.</span>`; }
async function renderDrawer() { const content = $("drawer-content"); if (state.drawer === "context") { content.innerHTML = `<div class="drawer-card"><strong>Current scope</strong>${escapeHtml(state.scope.title)}<br>Depth ${state.scope.depth}</div><div class="drawer-card"><strong>Editing model</strong>Changes are direct, traceable and undoable.</div>`; return; } if (state.drawer === "compare") { try { state.compare = await request("/api/compare", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ base: state.baseline, candidate: state.graph }) }); const c = state.compare; content.innerHTML = `<div class="drawer-card"><strong>Changes</strong>${c.nodesAdded.length} added · ${c.nodesRemoved.length} removed · ${c.nodesChanged.length} changed nodes</div><div class="drawer-card"><strong>Relationships</strong>${c.edgesAdded.length} added · ${c.edgesRemoved.length} removed</div>`; } catch (error) { content.textContent = error.message; } return; } if (state.drawer === "library") { const cards = [...state.library.patterns.map((item) => ({ ...item, kind: "Pattern" })), ...state.library.templates.map((item) => ({ ...item, kind: "Template" }))]; content.innerHTML = cards.length ? cards.map((item) => `<div class="drawer-card"><strong>${escapeHtml(item.kind)} · ${escapeHtml(item.title)}</strong>${escapeHtml(item.problem || item.target || "Reusable knowledge for the current scope.")}<br><button type="button" data-library="${escapeHtml(item.id)}">Preview in scope</button></div>`).join("") : `<span class="muted">Library is empty.</span>`; document.querySelectorAll("[data-library]").forEach((button) => button.addEventListener("click", () => toast(`Preview ${button.dataset.library} for ${state.scope.title}`))); return; } const tour = state.tour?.tour || state.tours[0]; if (!tour) { content.innerHTML = `<span class="muted">No guided tours configured.</span>`; return; } if (!state.tour) content.innerHTML = `<div class="drawer-card"><strong>${escapeHtml(tour.title)}</strong>${tour.steps.length} semantic steps<br><button id="start-tour" type="button">Start tour</button></div>`; else content.innerHTML = `<div class="drawer-card"><strong>${escapeHtml(tour.title)}</strong>Step ${state.tour.index + 1} of ${tour.steps.length}<br>${escapeHtml(tour.steps[state.tour.index].explanation)}<br><button id="tour-back" type="button" ${state.tour.index === 0 ? "disabled" : ""}>Back</button> <button id="tour-next" type="button">${state.tour.index === tour.steps.length - 1 ? "Finish" : "Next"}</button></div>`; $("start-tour")?.addEventListener("click", () => startTour(tour)); $("tour-back")?.addEventListener("click", () => { state.tour.index -= 1; showTourStep(); }); $("tour-next")?.addEventListener("click", () => { if (state.tour.index >= tour.steps.length - 1) { state.tour = null; render(); toast("Tour complete"); } else { state.tour.index += 1; showTourStep(); } }); }
async function renderAgentDrawer() {
  const content = $("drawer-content");
  if (state.drawer === "proposals") {
    content.innerHTML = state.proposals.length ? state.proposals.map((proposal) => `<div class="drawer-card"><strong>${escapeHtml(proposal.title)}</strong><br><span class="muted">${escapeHtml(proposal.status || "pending")} · ${escapeHtml(proposal.source || "agent")}</span><p>${escapeHtml(proposal.rationale || "No rationale provided.")}</p><button type="button" data-proposal-preview="${escapeHtml(proposal.id)}">Preview</button> <button type="button" data-proposal-apply="${escapeHtml(proposal.id)}" ${proposal.status !== "pending" ? "disabled" : ""}>Apply</button> <button type="button" data-proposal-reject="${escapeHtml(proposal.id)}" ${proposal.status !== "pending" ? "disabled" : ""}>Reject</button><div id="proposal-detail-${escapeHtml(proposal.id)}"></div></div>`).join("") : `<span class="muted">No agent proposals.</span>`;
    document.querySelectorAll("[data-proposal-preview]").forEach((button) => button.addEventListener("click", () => previewProposal(button.dataset.proposalPreview)));
    document.querySelectorAll("[data-proposal-apply]").forEach((button) => button.addEventListener("click", () => applyProposal(button.dataset.proposalApply)));
    document.querySelectorAll("[data-proposal-reject]").forEach((button) => button.addEventListener("click", () => rejectProposal(button.dataset.proposalReject)));
    return;
  }
  if (state.drawer === "context") {
    content.innerHTML += `<div class="drawer-card"><strong>Agent context</strong>Markdown is generated from the canonical JSON graph for the current project and focus.</div>`;
  }
  await renderDrawerOriginal(content);
}
async function renderDrawerOriginal(content) {
  if (state.drawer === "context") { content.innerHTML = `<div class="drawer-card"><strong>Current scope</strong>${escapeHtml(state.scope.title)}<br>Depth ${state.scope.depth}</div><div class="drawer-card"><strong>Editing model</strong>Changes are direct, traceable and undoable.</div><div class="drawer-card"><strong>Agent context</strong>Markdown is generated from the canonical JSON graph for the current project and focus.</div>`; return; }
  if (state.drawer === "compare") { try { state.compare = await request("/api/compare", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ base: state.baseline, candidate: state.graph }) }); const c = state.compare; content.innerHTML = `<div class="drawer-card"><strong>Changes</strong>${c.nodesAdded.length} added · ${c.nodesRemoved.length} removed · ${c.nodesChanged.length} changed nodes</div><div class="drawer-card"><strong>Relationships</strong>${c.edgesAdded.length} added · ${c.edgesRemoved.length} removed</div>`; } catch (error) { content.textContent = error.message; } return; }
  if (state.drawer === "library") { const cards = [...state.library.patterns.map((item) => ({ ...item, kind: "Pattern" })), ...state.library.templates.map((item) => ({ ...item, kind: "Template" }))]; content.innerHTML = cards.length ? cards.map((item) => `<div class="drawer-card"><strong>${escapeHtml(item.kind)} · ${escapeHtml(item.title)}</strong>${escapeHtml(item.problem || item.target || "Reusable knowledge for the current scope.")}<br><button type="button" data-library="${escapeHtml(item.id)}">Preview in scope</button></div>`).join("") : `<span class="muted">Library is empty.</span>`; document.querySelectorAll("[data-library]").forEach((button) => button.addEventListener("click", () => toast(`Preview ${button.dataset.library} for ${state.scope.title}`))); return; }
  const tour = state.tour?.tour || state.tours[0]; if (!tour) { content.innerHTML = `<span class="muted">No guided tours configured.</span>`; return; } if (!state.tour) content.innerHTML = `<div class="drawer-card"><strong>${escapeHtml(tour.title)}</strong>${tour.steps.length} semantic steps<br><button id="start-tour" type="button">Start tour</button></div>`; else content.innerHTML = `<div class="drawer-card"><strong>${escapeHtml(tour.title)}</strong>Step ${state.tour.index + 1} of ${tour.steps.length}<br>${escapeHtml(tour.steps[state.tour.index].explanation)}<br><button id="tour-back" type="button" ${state.tour.index === 0 ? "disabled" : ""}>Back</button> <button id="tour-next" type="button">${state.tour.index === tour.steps.length - 1 ? "Finish" : "Next"}</button></div>`; $("start-tour")?.addEventListener("click", () => startTour(tour)); $("tour-back")?.addEventListener("click", () => { state.tour.index -= 1; showTourStep(); }); $("tour-next")?.addEventListener("click", () => { if (state.tour.index >= tour.steps.length - 1) { state.tour = null; render(); toast("Tour complete"); } else { state.tour.index += 1; showTourStep(); } });
}
async function previewProposal(id) { try { const result = await request(`/api/proposals/${encodeURIComponent(id)}/preview`, { method: "POST" }); const target = $(`proposal-detail-${id}`); if (target) target.innerHTML = `<p><strong>Preview</strong> ${result.diff.nodesAdded.length} added · ${result.diff.nodesChanged.length} changed · ${result.diff.edgesAdded.length} relationships</p><p>${result.canApply ? "Ready for human approval." : "Cannot apply: stale or invalid."}</p>${result.diagnostics.length ? `<p class="muted">${result.diagnostics.map((item) => escapeHtml(item.message)).join("<br>")}</p>` : ""}`; } catch (error) { toast(error.message); } }
async function applyProposal(id) { if (!confirm("Apply this agent proposal to the canonical graph?")) return; try { const result = await request(`/api/proposals/${encodeURIComponent(id)}/apply`, { method: "POST" }); state.graph = result.graph; state.baseline = clone(result.graph); state.diagnostics = result.diagnostics || []; state.proposals = state.proposals.map((item) => item.id === id ? result.proposal : item); state.dirty = false; render(); toast("Proposal applied"); } catch (error) { toast(error.message); await refreshProposals(); } }
async function rejectProposal(id) { try { const result = await request(`/api/proposals/${encodeURIComponent(id)}/reject`, { method: "POST" }); state.proposals = state.proposals.map((item) => item.id === id ? result.proposal : item); render(); toast("Proposal rejected"); } catch (error) { toast(error.message); } }
async function refreshProposals() { const result = await request("/api/proposals"); state.proposals = result.proposals || []; }
function startTour(tour) { state.tour = { tour, index: 0 }; state.drawer = "tour"; showTourStep(); }
function showTourStep() { const step = state.tour.tour.steps[state.tour.index]; state.view = step.lens; const area = state.focusAreas.find((item) => item.id === step.scopeId); if (area) state.scope = { id: area.id, title: area.title, rootIds: area.rootIds, depth: area.depth }; state.selectedId = step.nodeId; render(); selectNode(step.nodeId); toast(`${state.tour.index + 1}/${state.tour.tour.steps.length}: ${step.explanation}`); }
function render() { renderFocusAreas(); renderLenses(); renderNodeList(); renderGraph(); renderInspector(); renderValidation(); $("scope-breadcrumb").textContent = state.scope.id === "project" ? "Project" : `Project / ${state.scope.title}`; setStatus(state.dirty ? "Unsaved changes" : "Ready"); renderAgentDrawer(); }

$("search").addEventListener("input", (event) => { state.search = event.target.value; render(); }); $("undo-button").addEventListener("click", undo); $("redo-button").addEventListener("click", redo); $("back-button").addEventListener("click", () => { const previous = state.scopeBack.pop(); if (!previous) return; state.scopeForward.push({ ...state.scope }); setScope(previous, false); }); $("forward-button").addEventListener("click", () => { const next = state.scopeForward.pop(); if (!next) return; state.scopeBack.push({ ...state.scope }); setScope(next, false); }); window.addEventListener("keydown", (event) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "z") { event.preventDefault(); event.shiftKey ? redo() : undo(); } });
$("isolate-button").addEventListener("click", () => { const node = selectedNode(); if (!node) return toast("Select an object first"); state.scope.depth = 0; state.scope.rootIds = [node.id]; render(); toast(`Isolated ${node.title}`); }); $("expand-button").addEventListener("click", () => { state.scope.depth = Math.min(8, state.scope.depth + 1); render(); toast(`Expanded to depth ${state.scope.depth}`); }); $("compare-button").addEventListener("click", () => { state.drawer = "compare"; renderAgentDrawer(); }); document.querySelectorAll("[data-drawer]").forEach((button) => button.addEventListener("click", () => { state.drawer = button.dataset.drawer; document.querySelectorAll("[data-drawer]").forEach((item) => item.classList.toggle("active", item === button)); renderAgentDrawer(); })); document.querySelectorAll("[data-tool]").forEach((button) => button.addEventListener("click", () => { state.drawer = button.dataset.tool === "library" ? "library" : button.dataset.tool === "review" ? "proposals" : "context"; document.querySelectorAll("[data-tool]").forEach((item) => item.classList.toggle("active", item === button)); renderAgentDrawer(); }));
$("focus-here-button").addEventListener("click", () => { const node = selectedNode(); if (!node) return; setScope({ id: `focus:${node.id}`, title: node.title, rootIds: [node.id], depth: 2 }); }); $("context-refresh").addEventListener("click", () => { if (state.selectedId) selectNode(state.selectedId); }); $("save-button").addEventListener("click", async () => { try { const response = await request("/api/workspace", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ graph: state.graph, layout: state.layout }) }); state.baseline = clone(state.graph); state.diagnostics = response.diagnostics || []; state.dirty = false; setStatus("Saved"); toast("Product model saved"); } catch (error) { toast(error.message); } });
$("node-form").addEventListener("submit", (event) => { event.preventDefault(); const node = selectedNode(); if (!node) return; try { const values = { title: $("node-title").value.trim(), type: $("node-type").value.trim(), region: $("node-region").value, status: $("node-status").value.trim() || undefined, data: JSON.parse($("node-data").value || "{}") }; commit(() => Object.assign(node, values)); toast("Product model updated"); } catch { toast("Metadata must be valid JSON"); } }); $("delete-node").addEventListener("click", () => { const node = selectedNode(); if (!node || !confirm(`Delete ${node.title}? Relationships will also be removed.`)) return; commit(() => { state.graph.nodes = state.graph.nodes.filter((item) => item.id !== node.id); state.graph.edges = state.graph.edges.filter((edge) => edge.from !== node.id && edge.to !== node.id); state.selectedId = null; }); }); $("add-node").addEventListener("click", () => { const title = prompt("Object title", "New product concept"); if (!title) return; const region = state.view === "domain" ? "domain" : state.view === "workflow" ? "workflow" : state.view === "experience" ? "experience" : "product"; const node = { id: `${region}:${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, type: region === "domain" ? "concept" : region, region, title, status: "draft", data: {} }; if (state.graph.nodes.some((item) => item.id === node.id)) return toast("An object with this ID already exists"); commit(() => { state.graph.nodes.push(node); state.selectedId = node.id; }); }); $("add-edge").addEventListener("click", () => { const node = selectedNode(); if (!node) return; const target = prompt("Target object ID", state.graph.nodes.find((item) => item.id !== node.id)?.id || ""); if (!target || !nodeById(target)) return toast("Target object was not found"); const kind = prompt("Relationship kind", "relates-to") || "relates-to"; commit(() => state.graph.edges.push({ id: `edge:${node.id}-${target}-${Date.now()}`, kind, from: node.id, to: target })); });

async function boot() { try { const response = await request("/api/workspace"); state.graph = response.graph; state.baseline = clone(response.baseline || response.graph); state.layout = response.layout || {}; state.focusAreas = response.focusAreas || []; state.tours = response.tours || []; state.library = response.library || { patterns: [], templates: [] }; state.diagnostics = response.diagnostics || []; await refreshProposals(); $("project-name").textContent = state.graph.manifest.name; render(); } catch (error) { $("project-name").textContent = "Unable to load project"; toast(error.message); } }
boot();
